"""
    Configurations which are required for any form of deployment
    To change any config based on deployment, please use the suitable config file.
"""
import os
from urllib import parse

# App Configs:
SECRET_KEY = b'VerySecretKey'
CORS_ORIGINS = {
    r"/*": {"origins": ["*"]}
}
DEBUG = True

# Auth:
# If you change these, please read through Argon2 docs first.
TIME_COST = 2
MEM_COST = 102400
PARALLEL = 8
PASS_HASH_LEN = 16
PASS_SALT_LEN = 16
TOKEN_EXP_MINUTES = 60*24

# Directories
CUR_DIR = os.path.dirname(__file__)

# MONGO DB:
MONGO_DB_URI = ""

# SQL DB:
SQL_DB_TYPE = ""
# SQL_DB_TYPE values:
# MySQL: mysql+mysqldb or mysql
# Postgres: postgres
SQL_DB_USER = ""
SQL_PASSWORD = ""
SQL_DB_HOST = ""
SQL_SQL_DB_PORT = ""
SQL_DATABASE = ""

# EMAIL CONFIG:
EMAIL_SERVER_HOST = ""
EMAIL_SERVER_PORT = 000
SMTP_EMAIL_SERVER_PORT = 000
EMAIL_SERVER_USER = ""
EMAIL_SERVER_USER_PASSWORD = ""
EMAIL_SENDER_NAME = ""
EMAIL_BODY = {
    "reset": """
        Dear Customer,
        
        Thank You for contacting us.
        Here is your reset link:
        {url}?key={token}
        Please do not share it with others, as this is very confidential.
        Best Regards,

        ----------------------------------------------------------------------
        This is an autogenerated email. Please do not reply.
    """,
}
# Here "reset" is the mail type. url and token are data variables
EMAIL_HEADER = {
    "reset": "Link to reset password",
}
